version: '3.8'

services:

  fronted:
    build:
      context: ./
    working_dir: /app
    ports:
      - 4209:4209
    volumes:
      - .:/app:delegated
    command: ["sh", "-c", "npm install && ng serve --host 0.0.0.0 --port 4209", "--live-reload"]
